services:
  microservicio-parametros:
    container_name: MicroservicioParametrosSAC
    build:
      context: ./MicroservicioParametrosSAC/MicroservicioParametrosSAC
      dockerfile: Dockerfile
    ports:
      - "5001:80"

  microservicio-solicitud:
    container_name: MicroservicioSolicitudSAC
    build:
      context: ./MicroservicioSolicitudSAC/MicroservicioSolicitudSAC
      dockerfile: Dockerfile
    ports:
      - "5002:80"
     
  microservicio-usuarios:
    container_name: MicroservicioUsuariosSAC
    build:
      context: ./MicroservicioUsuariosSAC/MicroservicioUsuariosSAC
      dockerfile: Dockerfile
    ports:
      - "5003:80"
      
  microservicio-historial:
    container_name: MicroservicioHistorialSolicitudesSAC
    build:
      context: ./MicroservicioHistorialSolicitudesSAC/MicroservicioHistorialSolicitudesSAC
      dockerfile: Dockerfile
    ports:
      - "5004:80"